"""auth-init

Revision ID: 000
Revises:
Create Date: 2023-11-05 20:14:58.931266

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "000"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="xi_auth",
    )
    op.create_index(
        "hash_index_users_email",
        "users",
        ["email"],
        unique=False,
        schema="xi_auth",
        postgresql_using="hash",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.CHAR(length=50), nullable=False),
        sa.Column("expiry", sa.DateTime(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("cross_site", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["xi_auth.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        schema="xi_auth",
    )
    op.create_index(
        "hash_index_session_token",
        "sessions",
        ["token"],
        unique=False,
        schema="xi_auth",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_session_token",
        table_name="sessions",
        schema="xi_auth",
        postgresql_using="hash",
    )
    op.drop_table("sessions", schema="xi_auth")
    op.drop_index(
        "hash_index_users_email",
        table_name="users",
        schema="xi_auth",
        postgresql_using="hash",
    )
    op.drop_table("users", schema="xi_auth")
    # ### end Alembic commands ###
