"""add-username

Revision ID: 001
Revises: 000
Create Date: 2023-11-12 11:09:15.935491

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = "000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.String(length=30), nullable=False),
        schema="xi_auth",
    )
    op.create_index(
        "hash_index_users_username",
        "users",
        ["username"],
        unique=False,
        schema="xi_auth",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_users_username",
        table_name="users",
        schema="xi_auth",
        postgresql_using="hash",
    )
    op.drop_column("users", "username", schema="xi_auth")
    # ### end Alembic commands ###
