"""basic_user_profile

Revision ID: 002
Revises: 001
Create Date: 2024-02-04 22:18:21.596829

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("display_name", sa.String(length=30), nullable=True),
        schema="xi_auth",
    )
    op.add_column(
        "users",
        sa.Column(
            "theme", sa.String(length=10), nullable=False, server_default="system"
        ),
        schema="xi_auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "theme", schema="xi_auth")
    op.drop_column("users", "display_name", schema="xi_auth")
    # ### end Alembic commands ###
