"""onboarding_stage

Revision ID: 003
Revises: 002
Create Date: 2024-02-25 17:50:10.632945

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    onboarding_enum = sa.Enum(
        "CREATED",
        "COMMUNITY_CHOICE",
        "COMMUNITY_CREATE",
        "COMMUNITY_INVITE",
        "COMPLETED",
        name="onboardingstage",
    )
    onboarding_enum.create(op.get_bind())

    op.add_column(
        "users",
        sa.Column(
            "onboarding_stage",
            onboarding_enum,
            nullable=False,
            server_default="CREATED",
        ),
        schema="xi_auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "onboarding_stage", schema="xi_auth")
    # ### end Alembic commands ###
