"""mub_sessions

Revision ID: 004
Revises: 003
Create Date: 2024-03-08 19:33:26.376381

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("mub", sa.Boolean(), nullable=False, server_default=sa.false()),
        schema="xi_auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "mub", schema="xi_auth")
    # ### end Alembic commands ###
