"""password_resetting

Revision ID: 005
Revises: 004
Create Date: 2024-03-14 18:53:02.605062

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("reset_token", sa.CHAR(length=15), nullable=True),
        schema="xi_auth",
    )
    op.add_column(
        "users",
        sa.Column(
            "last_password_change",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        schema="xi_auth",
    )
    op.create_index(
        "hash_index_users_token",
        "users",
        ["reset_token"],
        unique=False,
        schema="xi_auth",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "hash_index_users_token",
        table_name="users",
        schema="xi_auth",
        postgresql_using="hash",
    )
    op.drop_column("users", "last_password_change", schema="xi_auth")
    op.drop_column("users", "reset_token", schema="xi_auth")
    # ### end Alembic commands ###
