"""change_reset_token_length

Revision ID: 007
Revises: 006
Create Date: 2024-04-14 18:20:11.962335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token',
               existing_type=sa.CHAR(length=15),
               type_=sa.CHAR(length=50),
               existing_nullable=True,
               schema='xi_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token',
               existing_type=sa.CHAR(length=50),
               type_=sa.CHAR(length=15),
               existing_nullable=True,
               schema='xi_auth')
    # ### end Alembic commands ###
