"""email_confirmation_resending

Revision ID: 009
Revises: 008
Create Date: 2024-05-06 19:41:30.922393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "allowed_confirmation_resend",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
        schema="xi_auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "allowed_confirmation_resend", schema="xi_auth")
    # ### end Alembic commands ###
